- name: setting up db configuration
  hosts: local 
  become: yes
  vars:
    login_host : 174.129.117.9

  vars_prompt:
  - name: LP
    prompt: please enter my-sql login Password
    private: false   
  tasks:
  - name: install my-sql server
    ansible.builtin.dnf: 
      name: mysql-server
      state: latest

  - name: starting and enabling my-sql service   
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes  

  - name: installing python dependencies for mysql
    ansible.builtin.pip:
     name:
     - PyMySql
     - cryptography
     executable: pip3.9   

  - name: mysql user check 
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ LP }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: reg

  - name: set root password properly
    ansible.builtin.command:  mysql_secure_installation --set-root-pass ExpenseApp@1
    when: reg.failed is true
