- name: setting up db configuration
  hosts: db 
  become: yes
  vars:
    login_host: db.dilipswebsite.online
  vars_prompt:
    name: login_password
    prompt: please enter my-sql login password for root user
    private: no  
  tasks: 
  - name: installing mysql server 
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: starting and enabling mysql service 
    ansible.builtin.service:
      name: mysql    
      state: started 
      enabled: yes
  - name: downloading python dependencies for ansible
    ansible.builtin.pip:
      name:
      - pymysql
      - cryptography
      executable: pip3.9
  - name: checking if password is already set or not
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}" 
      filter: version
    ignore_errors: yes
    register: reg
  - name: print op
    ansible.builtin.debug:
      msg: "{{ reg }}"
 