- name: configuring frontend server
  hosts: frontend
  become: yes
  tasks:
    - name: install nginx 
      ansible.builtin.dnf:
       name: nginx
       state: latest

    - name: start and enable nginx
      ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes

    - name: delete default page
      ansible.builtin.file:
       path: /usr/share/nginx/html
       state: absent

    - name: create html directory 
      ansible.builtin.file:
       path: /usr/share/nginx/html
       state: directory

    - name: download and extract the code 
      ansible.builtin.unarchive:
       src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
       dest: /usr/share/nginx/html
       remote_src: yes   

    - name: restart nginx server
      ansible.builtin.service:
       name: nginx
       state: restarted
