 tasks: 
  - name: installing mysql server 
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: starting and enabling mysql server 
    ansible.builtin.service:
      name: mysqld
      state: started 
      enabled: yes
  - name: downloading python dependencies for mysql
    ansible.builtin.pip:
      name: 
      - pymysql
      - cryptography
      executable: pip3.9    
  - name: checking weather the root password is already set or not
    community.mysql.mysql_info: 
      login_user: root
      login_password: "{{ login_password }}"         
      login_host: "{{ login_host }}"
      filter: version
    register: reg  
    ignore_errors: yes
  - name: setting up root user password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"
    when: reg.failed is true